version: '2'
services:
  ansible:
    build: ansible/.
    links:
    - demo
    - front1
    - front2
    - server
    - mysql
    command: tail -F /var/log/test
    container_name: ansible
    volumes:
    - ./ansible/playbook/:/playbook/
  demo:
      build: centos6_with_ssh/.
      expose:
      - "22"
      expose:
      - "22"
      ports:
      - "83:80"
      container_name: demo
  front1:
    build: centos6_with_ssh/.
    links:
    - server
    expose:
    - "22"
    ports:
    - "80:80"
    container_name: front1
  front2:
      build: centos6_with_ssh/.
      links:
      - server
      expose:
      - "22"
      ports:
      - "81:80"
      container_name: front2
  server:
    build: centos6_with_ssh/.
    links:
    - mysql
    expose:
    - "22"
    - "80"
    ports:
    - "8081:80"
    container_name: server
  mysql:
    build: centos6_with_ssh/.
    expose:
    - "22"
    - "3306"
    ports:
    - "3306:3306"
    container_name: mysql
