---

- hosts: middle
  tasks:
    - name: Install Epel
      yum: name=epel-release
           state=present

- hosts: middle
  vars:
    zabbix_url: localhost
  roles:
    - ansible-role-apache-master
    - ansible-role-php-master
    - ansible-zabbix-server-master
