---

- hosts: middle
  tasks:
    - name: Install Epel
      yum: name=epel-release
           state=present

- hosts: middle
  vars:
    zabbix_url: localhost
  roles:
    - geerlingguy.apache
    - geerlingguy.php
    - ameausoone.zabbix-server
